//! The on-disk policy (`.agentfence/profile.toml`).

use crate::needs::{Need, Right};
use crate::roles::Role;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Rule {
    pub path: String,
    pub access: Vec<Right>,
    pub role: Role,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct Network {
    /// Enforce TCP port rules (Landlock ABI >= 4).
    pub enforce: bool,
    pub connect_tcp: Vec<u16>,
    pub bind_tcp: Vec<u16>,
    /// Informational: UDP ports seen (Landlock cannot restrict UDP).
    pub observed_udp: Vec<u16>,
    /// Informational: `ip:port` pairs seen. Landlock filters by port only;
    /// host-level filtering needs a netns + proxy (future work).
    pub observed_tcp_endpoints: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Hardening {
    /// Block signals to processes outside the sandbox (ABI >= 6).
    pub scope_signals: bool,
    /// Block connecting to abstract unix sockets outside the sandbox (ABI >= 6).
    pub scope_abstract_unix: bool,
}

impl Default for Hardening {
    fn default() -> Self {
        Hardening {
            scope_signals: true,
            scope_abstract_unix: true,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Profile {
    pub version: u32,
    pub project_root: String,
    pub home: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tmpdir: Option<String>,
    /// Trace files this profile was synthesized from.
    #[serde(default)]
    pub traces: Vec<String>,
    /// Secret paths the agent touched during learning; deliberately NOT granted.
    #[serde(default)]
    pub blocked_secrets: Vec<String>,
    /// Needs that could not be granted without exposing a protected path.
    #[serde(default)]
    pub unmet: Vec<String>,
    #[serde(default)]
    pub warnings: Vec<String>,
    #[serde(default)]
    pub network: Network,
    #[serde(default)]
    pub hardening: Hardening,
    #[serde(default)]
    pub rules: Vec<Rule>,
}

impl Profile {
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading profile {}", path.display()))?;
        toml::from_str(&text).with_context(|| format!("parsing profile {}", path.display()))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let body = toml::to_string_pretty(self).context("serializing profile")?;
        let header = "# agentfence profile: generated by `agentfence synth`. Review before trusting.\n\
                      # Rights: read_file, read_dir, write (create/remove/rename/truncate), exec, connect_unix.\n\n";
        std::fs::write(path, format!("{header}{body}"))
            .with_context(|| format!("writing {}", path.display()))
    }

    /// Would the profile's filesystem rules allow this need?
    pub fn allows(&self, need: &Need) -> bool {
        self.rules
            .iter()
            .any(|r| r.access.contains(&need.right) && need.covered_by(Path::new(&r.path)))
    }

    /// Roles are computed on demand so `report` works on hand-edited profiles.
    pub fn ctx(&self) -> crate::roles::Ctx {
        crate::roles::Ctx {
            home: PathBuf::from(&self.home),
            project: PathBuf::from(&self.project_root),
            tmpdir: self.tmpdir.as_ref().map(PathBuf::from),
        }
    }

    pub fn is_tcp_connect_allowed(&self, port: u16) -> bool {
        !self.network.enforce || self.network.connect_tcp.contains(&port)
    }
}

/// Render `p` with `~` for the profile's home (display only).
pub fn tilde(p: &str, home: &str) -> String {
    if !home.is_empty() {
        if p == home {
            return "~".into();
        }
        if let Some(rest) = p.strip_prefix(&format!("{home}/")) {
            return format!("~/{rest}");
        }
    }
    p.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::needs::NeedKind;

    fn sample() -> Profile {
        Profile {
            version: 1,
            project_root: "/p".into(),
            home: "/h".into(),
            tmpdir: None,
            traces: vec!["t1".into()],
            blocked_secrets: vec!["~/.ssh/id_rsa (read)".into()],
            unmet: vec![],
            warnings: vec!["w".into()],
            network: Network {
                enforce: true,
                connect_tcp: vec![443],
                ..Default::default()
            },
            hardening: Hardening::default(),
            rules: vec![
                Rule {
                    path: "/p".into(),
                    access: vec![Right::ReadFile, Right::Write],
                    role: Role::Project,
                },
                Rule {
                    path: "/usr".into(),
                    access: vec![Right::Exec],
                    role: Role::Toolchain,
                },
            ],
        }
    }

    #[test]
    fn toml_roundtrip() {
        let d = tempfile::tempdir().unwrap();
        let f = d.path().join("profile.toml");
        sample().save(&f).unwrap();
        assert_eq!(Profile::load(&f).unwrap(), sample());
    }

    #[test]
    fn allows_respects_right_and_kind() {
        let p = sample();
        assert!(p.allows(&Need::new("/p/a/b", Right::ReadFile, NeedKind::Exact)));
        assert!(!p.allows(&Need::new("/p/a/b", Right::Exec, NeedKind::Exact)));
        assert!(!p.allows(&Need::new("/p", Right::Write, NeedKind::Entry)));
        assert!(p.allows(&Need::new("/p/x", Right::Write, NeedKind::Entry)));
        assert!(!p.allows(&Need::new(
            "/home/.ssh/id",
            Right::ReadFile,
            NeedKind::Exact
        )));
    }

    #[test]
    fn tilde_display() {
        assert_eq!(tilde("/h/.ssh/id", "/h"), "~/.ssh/id");
        assert_eq!(tilde("/hx/a", "/h"), "/hx/a");
    }
}
