//! `profile.rules`: a flat, line-based compiled form of a profile that a
//! launcher written in C (or anything without a TOML parser) can consume.
//! The format is specified in `docs/PROFILE_FORMAT.md`.

use crate::needs::Right;
use crate::profile::Profile;
use anyhow::{bail, Result};
use std::path::Path;

/// Header written by `compile` (format version 2).
pub const HEADER: &str = "agentfence-rules 2";
/// Version 1 is still accepted by the parser (no `resolve_unix`, no `option`).
pub const HEADER_V1: &str = "agentfence-rules 1";

/// Landlock right names in canonical output order.
const ORDER: &[&str] = &[
    "execute",
    "write_file",
    "read_file",
    "read_dir",
    "remove_dir",
    "remove_file",
    "make_char",
    "make_dir",
    "make_reg",
    "make_sock",
    "make_fifo",
    "make_block",
    "make_sym",
    "refer",
    "truncate",
    "ioctl_dev",
    "resolve_unix",
];

/// Rights valid on a non-directory.
const FILE_OK: &[&str] = &[
    "execute",
    "write_file",
    "read_file",
    "truncate",
    "ioctl_dev",
    "resolve_unix",
];

fn expand(r: Right) -> &'static [&'static str] {
    match r {
        Right::ReadFile => &["read_file"],
        Right::ReadDir => &["read_dir"],
        Right::Exec => &["execute"],
        Right::Write => &[
            "write_file",
            "truncate",
            "make_reg",
            "make_dir",
            "make_sym",
            "make_sock",
            "make_fifo",
            "remove_file",
            "remove_dir",
            "refer",
        ],
        Right::ConnectUnix => &["resolve_unix"],
    }
}

/// A parsed `profile.rules` line.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RuleLine {
    Fs {
        path: String,
        rights: Vec<String>,
    },
    Net {
        kind: String,
        port: u16,
    },
    /// Version 2 only: `option<TAB>name`.
    Opt {
        name: String,
    },
}

/// Compile a profile. `is_dir` decides whether a path may carry directory-only
/// rights (non-directories get the file-valid subset).
pub fn compile(profile: &Profile, is_dir: &dyn Fn(&Path) -> bool) -> Result<String> {
    let mut out = format!(
        "{HEADER}\n# generated by `agentfence synth`; edit profile.toml and re-run synth instead\n"
    );
    if profile.network.enforce {
        out.push_str("option\tnet_enforce\n");
    }
    if profile.hardening.scope_signals {
        out.push_str("option\tscope_signal\n");
    }
    if profile.hardening.scope_abstract_unix {
        out.push_str("option\tscope_abstract_unix\n");
    }
    for r in &profile.rules {
        if r.path.contains('\t') || r.path.contains('\n') || r.path.contains('\r') {
            bail!("rule path contains a tab or newline and cannot be represented in profile.rules: {:?}", r.path);
        }
        let dir = is_dir(Path::new(&r.path));
        let mut rights: Vec<&str> = r
            .access
            .iter()
            .flat_map(|a| expand(*a).iter().copied())
            .collect();
        if !dir {
            rights.retain(|x| FILE_OK.contains(x));
        }
        rights.sort_by_key(|x| ORDER.iter().position(|o| o == x));
        rights.dedup();
        if rights.is_empty() {
            continue;
        }
        out.push_str(&format!("fs\t{}\t{}\n", r.path, rights.join(",")));
    }
    if profile.network.enforce {
        for p in &profile.network.connect_tcp {
            out.push_str(&format!("net\tconnect\t{p}\n"));
        }
        for p in &profile.network.bind_tcp {
            out.push_str(&format!("net\tbind\t{p}\n"));
        }
    }
    Ok(out)
}

/// Reference parser (the C launcher implements the same grammar).
pub fn parse(text: &str) -> Result<Vec<RuleLine>> {
    let mut lines = text.lines();
    let version = match lines.next() {
        Some(HEADER_V1) => 1,
        Some(HEADER) => 2,
        _ => bail!("missing or unsupported header (expected `{HEADER_V1}` or `{HEADER}`)"),
    };
    let mut out = Vec::new();
    for (n, line) in lines.enumerate() {
        let n = n + 2;
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        match f.as_slice() {
            ["fs", path, rights] => {
                if !path.starts_with('/') {
                    bail!("line {n}: path must be absolute");
                }
                let rights: Vec<String> = rights.split(',').map(String::from).collect();
                let known = |r: &str| ORDER.contains(&r) && (version >= 2 || r != "resolve_unix");
                if let Some(bad) = rights.iter().find(|r| !known(r)) {
                    bail!("line {n}: unknown right `{bad}`");
                }
                out.push(RuleLine::Fs {
                    path: path.to_string(),
                    rights,
                });
            }
            ["net", kind @ ("connect" | "bind"), port] => {
                // Digits only: `u16::from_str` would also accept a leading `+`.
                let port = Some(port)
                    .filter(|p| p.bytes().all(|b| b.is_ascii_digit()))
                    .and_then(|p| p.parse().ok())
                    .ok_or_else(|| anyhow::anyhow!("line {n}: bad port `{port}`"))?;
                out.push(RuleLine::Net {
                    kind: kind.to_string(),
                    port,
                });
            }
            ["option", name @ ("net_enforce" | "scope_signal" | "scope_abstract_unix")]
                if version >= 2 =>
            {
                out.push(RuleLine::Opt {
                    name: name.to_string(),
                });
            }
            _ => bail!("line {n}: malformed rule"),
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profile::{Hardening, Network, Rule};
    use crate::roles::Role;

    fn profile(rules: Vec<Rule>) -> Profile {
        Profile {
            version: 1,
            project_root: "/p".into(),
            home: "/h".into(),
            tmpdir: None,
            traces: vec![],
            blocked_secrets: vec![],
            unmet: vec![],
            warnings: vec![],
            network: Network {
                enforce: true,
                connect_tcp: vec![443, 8080],
                bind_tcp: vec![0],
                ..Default::default()
            },
            hardening: Hardening::default(),
            rules,
        }
    }

    fn rule(path: &str, a: &[Right]) -> Rule {
        Rule {
            path: path.into(),
            access: a.to_vec(),
            role: Role::Other,
        }
    }

    #[test]
    fn compile_and_parse_round_trip() {
        let p = profile(vec![
            rule("/p", &[Right::ReadFile, Right::ReadDir, Right::Write]),
            rule("/usr/bin/git", &[Right::Exec, Right::ReadFile]),
            rule("/dev/null", &[Right::Write]),
            rule("/run/x.sock", &[Right::ConnectUnix]),
        ]);
        let text = compile(&p, &|path| {
            path != Path::new("/usr/bin/git")
                && path != Path::new("/dev/null")
                && path != Path::new("/run/x.sock")
        })
        .unwrap();
        assert!(text.starts_with("agentfence-rules 2\n"));
        let parsed = parse(&text).unwrap();
        assert_eq!(
            parsed,
            vec![
                RuleLine::Opt { name: "net_enforce".into() },
                RuleLine::Opt { name: "scope_signal".into() },
                RuleLine::Opt { name: "scope_abstract_unix".into() },
                RuleLine::Fs {
                    path: "/p".into(),
                    rights: "write_file,read_file,read_dir,remove_dir,remove_file,make_dir,make_reg,make_sock,make_fifo,make_sym,refer,truncate"
                        .split(',')
                        .map(String::from)
                        .collect()
                },
                RuleLine::Fs { path: "/usr/bin/git".into(), rights: vec!["execute".into(), "read_file".into()] },
                RuleLine::Fs { path: "/dev/null".into(), rights: vec!["write_file".into(), "truncate".into()] },
                RuleLine::Fs { path: "/run/x.sock".into(), rights: vec!["resolve_unix".into()] },
                RuleLine::Net { kind: "connect".into(), port: 443 },
                RuleLine::Net { kind: "connect".into(), port: 8080 },
                RuleLine::Net { kind: "bind".into(), port: 0 },
            ]
        );
    }

    #[test]
    fn rejects_tab_and_newline_in_paths() {
        for bad in ["/a\tb", "/a\nb"] {
            let p = profile(vec![rule(bad, &[Right::ReadFile])]);
            assert!(compile(&p, &|_| true).is_err());
        }
    }

    #[test]
    fn parser_rejects_garbage() {
        assert!(parse("nope\n").is_err());
        assert!(parse("agentfence-rules 1\nfs\trel\tread_file\n").is_err());
        assert!(parse("agentfence-rules 1\nfs\t/a\tfly\n").is_err());
        assert!(parse("agentfence-rules 1\nnet\tconnect\tabc\n").is_err());
        assert!(parse("agentfence-rules 1\n# c\n\n").unwrap().is_empty());
        assert!(parse("agentfence-rules 2\n# c\n\n").unwrap().is_empty());
        assert!(parse("agentfence-rules 3\n").is_err());
        assert!(parse("agentfence-rules 2\nnet\tconnect\t+80\n").is_err());
        assert!(parse("agentfence-rules 2\nnet\tconnect\t65536\n").is_err());
    }

    #[test]
    fn version_gates_new_syntax() {
        let sock = "fs\t/run/x.sock\tresolve_unix\n";
        assert!(parse(&format!("agentfence-rules 2\n{sock}")).is_ok());
        assert!(parse(&format!("agentfence-rules 1\n{sock}")).is_err());
        assert!(parse("agentfence-rules 2\noption\tscope_signal\n").is_ok());
        assert!(parse("agentfence-rules 2\noption\tbogus\n").is_err());
        assert!(parse("agentfence-rules 1\noption\tscope_signal\n").is_err());
    }

    #[test]
    fn options_follow_profile() {
        let mut p = profile(vec![]);
        p.network.enforce = false;
        p.hardening.scope_signals = false;
        let text = compile(&p, &|_| true).unwrap();
        assert!(!text.contains("net_enforce") && !text.contains("scope_signal"));
        assert!(text.contains("option\tscope_abstract_unix\n"));
    }
}
